### ISSUE TITLE
cli integration

### ISSUE THREAD

**Issue by feraxhp** [TakumiBC/zed-windows#1]
Hi bro, i know this a branch, but can we try to add the shell functionality to this build? you know that the cli integration is important.

**Comment by TakumiBC** [comment]
Hey @feraxhp! This project was based on the manual provided at https://github.com/zed-industries/zed/blob/main/docs/src/development/windows.md, and I didn't find any instructions about the shell. I could help with it if you would be able to provide the instructions.

**Comment by feraxhp** [comment]
Yeah, i was reading the code, it is no jet implemented for windows, when a update appears i will coment here.
